package org.springblade.modules.business.imcommand.enums;

public enum EnumImCommandRoute {
	TXN_INCOME,
	TXN_EXPENSE,
	MENU,
	TXN_UNDO,
	STATS_PRIVATE,
	TXN_LIST,
	GROUP_INVITE,
	GROUP_JOIN,
	GROUP_MEMBER_LIST,
	USER_NICKNAME_UPDATE,
	GROUP_MEMBER_ALIAS,
	GROUP_MEMBER_REMOVE,
	GROUP_QUIT,
	EXPORT_EXCEL,
	CONSUMPTION_ANALYSIS,
	BUDGET_SET,
	BUDGET_QUERY,
	AI_PARSE
}
